### ISSUE TITLE
Tree Gathering bug

### ISSUE THREAD

**Issue by Hadrix420** [Lcraft-Developers/RealisticMod#1]
Trees give you around 16000 leaves and planks each swing. Tried downgrading to 1 patch prior, same issue but it was 50 this time. It has something to do with the itemnet code or maybe you altered tree gathering? I narrowed it down. It happens on version 1.5 and 1.6.
1.4 works fine.

**Comment by LPDMinecraft** [comment]
Fixed in Version 1.7
